// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiDuGOSpX6SNEA27no5JkaekS1a1GtNC8',
    appId: '1:691939898543:web:b3183d0cbe59394d1b505a',
    messagingSenderId: '691939898543',
    projectId: 'soccer-app-flutter',
    authDomain: 'soccer-app-flutter.firebaseapp.com',
    storageBucket: 'soccer-app-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg_Ex83x3GVzpvEn3QMVRuhgbSngslYHs',
    appId: '1:691939898543:android:3f556af2479fc6e11b505a',
    messagingSenderId: '691939898543',
    projectId: 'soccer-app-flutter',
    storageBucket: 'soccer-app-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU7hiV5b_mo4KFzJCROHYcQzAuPD2jx9k',
    appId: '1:691939898543:ios:45839fd07e3e23141b505a',
    messagingSenderId: '691939898543',
    projectId: 'soccer-app-flutter',
    storageBucket: 'soccer-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.soccerAppFlutter.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU7hiV5b_mo4KFzJCROHYcQzAuPD2jx9k',
    appId: '1:691939898543:ios:4ff270b340aa354a1b505a',
    messagingSenderId: '691939898543',
    projectId: 'soccer-app-flutter',
    storageBucket: 'soccer-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.soccerAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiDuGOSpX6SNEA27no5JkaekS1a1GtNC8',
    appId: '1:691939898543:web:f2e0f4be12594fd51b505a',
    messagingSenderId: '691939898543',
    projectId: 'soccer-app-flutter',
    authDomain: 'soccer-app-flutter.firebaseapp.com',
    storageBucket: 'soccer-app-flutter.firebasestorage.app',
  );
}
