// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;
import 'dart:io';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: Platform.environment['FIREBASE_ANDROID_API_KEY'] ?? '',
    appId: Platform.environment['FIREBASE_ANDROID_APP_ID'] ?? '',
    messagingSenderId:
        Platform.environment['FIREBASE_MESSAGING_SENDER_ID'] ?? '',
    projectId: Platform.environment['FIREBASE_PROJECT_ID'] ?? '',
    storageBucket: Platform.environment['FIREBASE_STORAGE_BUCKET'] ?? '',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: Platform.environment['FIREBASE_IOS_API_KEY'] ?? '',
    appId: Platform.environment['FIREBASE_IOS_APP_ID'] ?? '',
    messagingSenderId:
        Platform.environment['FIREBASE_MESSAGING_SENDER_ID'] ?? '',
    projectId: Platform.environment['FIREBASE_PROJECT_ID'] ?? '',
    storageBucket: Platform.environment['FIREBASE_STORAGE_BUCKET'] ?? '',
    iosBundleId: 'jp.ac.saitama-u.mech.human.soccerAppFlutter',
  );
}
