name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: stable
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Check formatting
        run: dart format --set-exit-if-changed .

      - name: Analyze project
        run: flutter analyze
      
      - name: Run tests
        run: flutter test --coverage

      # Android のビルド
      # - name: Build Android (APK)
      #   run: flutter build apk --debug
